import type { Metadata } from 'next'
import { inter } from '@/lib/fonts'
import Footer from '@/components/Footer'
import './globals.css'

export const metadata: Metadata = {
  title: 'CBET Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
