import type { Metadata } from 'next'
import { inter } from '@/lib/fonts'
import './globals.css'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'CBET Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body
      className={`${inter.className} flex flex-col antialiased dark:bg-[url('/grid.svg')] dark:bg-[rgb(10,10,11)]`}>
        <div
          className='fixed h-screen w-screen blur-3xl z-[-1] opacity-[0.2] bg-gradient-to-br from-indigo-300 dark:from-fuchsia-700/20 via-gray-300 dark:via-blue-700/20 to-rose-400 dark:to-rose-700/20'
        />
        <div className='flex flex-col items-center justify-center w-full p-3'>
          <NavBar />
          <div className="bg-vc-border-gradient-light dark:bg-vc-border-gradient-dark p-px rounded-2xl mt-[7em] max-sm:mt-4 mb-4 w-full max-w-4xl">
            <main
              className='bg-white dark:bg-black rounded-2xl p-3 space-y-5'
            >
            {children}
          </main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
