import type { Metadata } from 'next'
import { inter } from '@/lib/fonts'
import Footer from '@/components/Footer'
import Image from 'next/image'
import './globals.css'

export const metadata: Metadata = {
  title: 'CBET Hub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col antialiased bg-[url('/grid.svg')] dark:bg-black`}>
        {/* <Image
          src='grid.svg'
          alt='background image'
          width={1000}
          height={1000}
          className='fixed top-0 left-0 w-full h-full z-[-1]'
        /> */}
        {children}
        <Footer />
      </body>
    </html>
  )
}
